apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - crc-rtgqw-master-0
  storageClassDevices:
    - storageClassName: "local-sc"
      volumeMode: Filesystem
      fsType: ext4
      devicePaths:
        - /dev/loop0
        - /dev/loop1
